### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by EXperementatorAV** [qoala101/esc#1]
At the moment it does not run on WIN 7 SP1, if it should run, I can provide more information about the system.
Thanks for the work, very useful application, I'm not a developer, but if you need help, I can try to help with ideas

**Comment by qoala101** [comment]
Hi,

In order to run the release executable from ponc-x.x.x-windows.zip on Win7 SP1 there are following prerequisites:

1. Have GPU which supports DirectX 11.

2. Install latest C++ runtime. This fixes errors of mssing VC*.dlls (also allows to build the app from sources).
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
Look for "Permalink for latest supported x64 version."

3. Install fix for missing D3DCompiler_47.dll (probably added in future service packs).
https://support.microsoft.com/en-us/topic/the-net-framework-4-7-installation-is-blocked-on-windows-7-windows-server-2008-r2-and-windows-server-2012-because-of-a-missing-d3dcompiler-update-0869046a-0972-7824-1bb8-5d89bf99e112
Look for "On Windows 7 SP1 or Windows Server 2008 R2 x64, use this link."

I'm able to verify it on VirtualBox which runs clear Win7 SP1 with the mentioned setup. 
I assumed that possible Win7 users would already have all the prerequisites installed by other means, but now I see that I should add this to README.

PONC currently doesn't support DirectX 9, but I have plans to add the support in near future since one of the users requests it.

Thanks for bringing this up! I appreciate it. I'll write you if I need any help.

**Comment by EXperementatorAV** [comment]
Very strange, but nothing helped me.
1. DirectX 11 - installed
2. C++ from your link is also installed
3. the download link does not work, but it seems that this file is already present
On win 10 on a colleague's computer it starts without problems, but unfortunately not on mine

**Comment by qoala101** [comment]
During testing on Win7 I encountered 2 types of problems:

1. Missing DLL errors like the following:
![image](https://github.com/qoala101/ponc/assets/97284265/377fe49c-d9af-42dc-b04f-cfb38d95b24f)
Fixed by mentioned installation. If you don't see the error dialog like this, then you most probably have all requirements installed.

2. App just won't start and doesn't bring up any error dialogs.  
This issue appeared in two cases:
- User tried to start the app from the archive without unpacking.  
Solution was to unpack and verify the presence of **data** folder in the executable directory. On my tests I just unpack it on the desktop.
![image](https://github.com/qoala101/ponc/assets/97284265/2b33cedf-9c3a-4799-9fc1-c7a00f439ee7)
![image](https://github.com/qoala101/ponc/assets/97284265/b302a39d-3751-4805-924c-b18042ab23ce)
- User had DirectX installed, but GPU didn't support it. This can be checked by running dxdiag (Start->cmd->dxdiag) or by checking whether GPU supports DirectX 11 on the internet.
This is how it looks on my Win7 VM (Good):
![image](https://github.com/qoala101/ponc/assets/97284265/defb6aef-3e01-448a-a9f1-7fa3767db3e6)
And this it how it looks on the user's machine (Bad):
![image](https://github.com/qoala101/ponc/assets/97284265/2303aa05-c27a-48b3-b778-535b3cd8aa46)

Currently app doesn't have any crash reporting mechanism which would allow me know what exactly is causing a problem on your side. Also I do not have much experience of determining the cause of issues on Windows. Even if I knew full info about your system, I wouldn't be able to figure it out.

At this point, the only possible way for me to know the issue on your side, is for you to build the app from sources, start it in debug mode and send me the call stack of the crash. If I get call stack, I'd take a look at it and attempt to fix it.

**Comment by EXperementatorAV** [comment]
Yes, it turns out my integrated GPU only supports DirectX 10.1. I have already lost the habit of such problems before working only with my home computer) I will now make a separate topic with some suggestions and one with an error that I managed to notice while watching the program on another PC
Thank you so much for your time
