### ISSUE TITLE
Additional parameters with signal attenuation

### ISSUE THREAD

**Issue by EXperementatorAV** [qoala101/esc#3]
There is not enough opportunity to enter your own attenuation parameters, since the network can be built in different ways, using, for example, fast connections on which there are more losses.
It is also important to add attenuation on the cable, somewhere it can be critical. That is, for the cable you enter the length and attenuation per km, the global setting may be enough
I thought that it would be possible to complicate the price calculator, but probably this does not make sense, you can calculate the cost of work in advance 1 time

**Comment by qoala101** [comment]
Just consulted with one of my users about this. He mentioned that in their scenarios, cable attenuation is negligible because they mostly work with the local networks. Also he mentioned that there are other sources of attenuation like 0.03 on wielding points or 0.2 on physical connection, etc.

I like your suggestion for cable attenuation though. Having an ability for each link to specify its length and custom attenuation, as well as a global setting sounds like an interesting thing to work on.
I plan to include it in one of the nearest releases. I don't work on the app full time, so it might take a few weeks.

As for Calculator feature, currently it can be used only for what it can do. There are plans to add features which would make the app actually usable for automatic analysis and network building based on requirements. I plan to get to it when I finish with the list of requested UI/UX features I have.

**Comment by EXperementatorAV** [comment]
Great, I'll be looking forward to it, good luck

**Comment by qoala101** [comment]
Added described functionality in the new release:
https://github.com/qoala101/ponc/releases/tag/v0.6.0
